name: catalog_grid
description: >-
  Catalog Grid.
  Provides a Catalog template of a grid of items.
version: 1.0.0
repository: https://github.com/LCostaN/catalog_grid
homepage: https://github.com/LCostaN/catalog_grid

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
